name: aliyun_oss
description: A new Flutter package project.
version: 1.1.0
homepage: https://github.com/dev-zhang/aliyun_oss

environment:
  sdk: '>=2.12.0 <3.0.0'
  flutter: ">=1.17.0 <2.0.0"

dependencies:
  dio: ^4.0.0
  crypto: ^3.0.1

dev_dependencies: 
  test: ^1.17.12
