name: aliyun_oss
description: A Dart package that helps to use aliyun object storage service (OSS).
version: 1.1.0
homepage: https://github.com/dev-zhang/aliyun_oss
repository: https://github.com/dev-zhang/aliyun_oss
issue_tracker: https://github.com/dev-zhang/aliyun_oss
documentation: https://github.com/dev-zhang/aliyun_oss

environment:
  sdk: '>=2.16.0 <3.0.0'

dependencies:
  dio: ^4.0.0
  crypto: ^3.0.1

dev_dependencies: 
  lints: ^1.0.1
  test: ^1.17.12
